AIRPORT_NAMES = {
    "ATL": "Atlanta Hartsfield-Jackson",
    "LAX": "Los Angeles International",
    "ORD": "Chicago O'Hare",
    "DFW": "Dallas/Fort Worth",
    "DEN": "Denver International",
    "JFK": "New York JFK",
    "SFO": "San Francisco International",
    "SEA": "Seattle-Tacoma",
    "LAS": "Las Vegas Harry Reid",
    "MCO": "Orlando International",
    "EWR": "Newark Liberty",
    "MIA": "Miami International",
    "CLT": "Charlotte Douglas",
    "PHX": "Phoenix Sky Harbor",
    "IAH": "Houston George Bush",
    "BOS": "Boston Logan",
    "MSP": "Minneapolis-Saint Paul",
    "DTW": "Detroit Metropolitan",
    "FLL": "Fort Lauderdale-Hollywood",
    "LGA": "New York LaGuardia",
    "BWI": "Baltimore/Washington",
    "SLC": "Salt Lake City International",
    "MDW": "Chicago Midway",
    "IAD": "Washington Dulles",
    "DCA": "Washington Reagan National",
    "SAN": "San Diego International",
    "TPA": "Tampa International",
    "BNA": "Nashville International",
    "AUS": "Austin-Bergstrom",
    "HOU": "Houston Hobby",
    "DAL": "Dallas Love Field",
    "PDX": "Portland International",
    "STL": "St. Louis Lambert",
    "HNL": "Honolulu Daniel K. Inouye",
    "MCI": "Kansas City International",
    "OAK": "Oakland International",
    "RDU": "Raleigh-Durham",
    "MSY": "New Orleans Louis Armstrong",
    "SMF": "Sacramento International",
    "SJC": "San Jose International",
    "PHL": "Philadelphia International",
    "CLE": "Cleveland Hopkins",
    "PIT": "Pittsburgh International",
    "IND": "Indianapolis International",
    "CMH": "Columbus John Glenn",
    "CVG": "Cincinnati/Northern Kentucky",
    "MKE": "Milwaukee Mitchell",
    "BUF": "Buffalo Niagara",
    "OGG": "Maui Kahului",
    "ANC": "Anchorage Ted Stevens",
    "FAI": "Fairbanks International",
    "ABQ": "Albuquerque International",
    "TUS": "Tucson International",
    "ELP": "El Paso International",
    "OMA": "Omaha Eppley",
    "MEM": "Memphis International",
    "BHM": "Birmingham-Shuttlesworth",
    "JAX": "Jacksonville International",
    "SAT": "San Antonio International",
    "RSW": "Fort Myers Southwest Florida",
    "PBI": "Palm Beach International",
    "SRQ": "Sarasota-Bradenton",
    "GEG": "Spokane International",
    "BOI": "Boise Airport",
    "RNO": "Reno-Tahoe International",
    "LGB": "Long Beach Airport",
    "BUR": "Hollywood Burbank",
    "ONT": "Ontario International",
    "SNA": "Orange County John Wayne",
    "SBN": "South Bend International",
    "MSN": "Madison Dane County",
    "BZN": "Bozeman Yellowstone",
    "FAT": "Fresno Yosemite",
    "LIT": "Little Rock Clinton",
    "TUL": "Tulsa International",
    "OKC": "Oklahoma City Will Rogers",
    "ICT": "Wichita Eisenhower",
    "DSM": "Des Moines International",
    "GRR": "Grand Rapids Gerald Ford",
    "ROC": "Rochester Greater",
    "SYR": "Syracuse Hancock",
    "ALB": "Albany International",
    "PVD": "Providence T.F. Green",
    "MHT": "Manchester-Boston Regional",
    "BTV": "Burlington International",
    "PWM": "Portland International Jetport",
    "BGR": "Bangor International",
}

def airport_label(code: str) -> str:
    name = AIRPORT_NAMES.get(code)
    return f"{code} — {name}" if name else code

AIRLINE_NAMES = {
    "AA": "American", "DL": "Delta",     "WN": "Southwest", "UA": "United",
    "AS": "Alaska",   "B6": "JetBlue",   "NK": "Spirit",    "F9": "Frontier",
    "HA": "Hawaiian", "G4": "Allegiant", "OO": "SkyWest",   "9E": "Endeavor",
    "MQ": "Envoy",    "YX": "Republic",  "OH": "PSA",       "QX": "Horizon",
    "YV": "Mesa",
}

AIRLINE_CODES = sorted(AIRLINE_NAMES.keys())

def airline_label(code):
    return f"{AIRLINE_NAMES.get(code, code)} ({code})"

MODEL_PATHS = {
    "classifier":   "models/lgbm_classifier.joblib",
    "regressor":    "models/lgbm_regressor.joblib",
    "encoder":      "models/ordinal_encoder.joblib",
    "top_orig":     "models/top_orig.joblib",
    "top_dest":     "models/top_dest.joblib",
    "route_data":   "models/route_avg_delay.joblib",
    "preprocessor": "models/preprocessor_sample.joblib",
    "insights":     "models/insights_stats.joblib",
}
